version: "3.9"
services:
  app:
    build:
      context: .
      target: dev
    entrypoint: ["/app/entrypoint.sh"]
    init: true
    environment:
      DATABASE_HOST: database
      DATABASE_HOST_RO: database
      DATABASE_NAME: service
      DATABASE_PASSWORD: service-password
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-network


  database:
    image: public.ecr.aws/docker/library/postgres:13.3
    environment:
      POSTGRES_DB: service
      POSTGRES_PASSWORD: service-password
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d service"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
